### ISSUE TITLE
bash: HTTP: command not found

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/rc-assistant#3]
when trying "HTTP PUT https://<lambda-server>/prod/admin/setup-database"

**Comment by zxdong262** [comment]
I guess it should be replaced with `curl -X PUT -u admin:admin http://localhost:3000/admin/setup-database`

**Comment by tylerlong** [comment]
It is just pseudocode. 

And by the time I wrote the doc, there was no admin auth feature

**Comment by tylerlong** [comment]
Updated
