### ISSUE TITLE
Got some aws related error

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/rc-assistant#5]
UnhandledPromiseRejectionWarning: MultipleValidationErrors: There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'botName' in params
* MissingRequiredParameter: Missing required key 'botAlias' in params
    at ParamValidator.validate (/Users/drake.zhao/try/rc-assistant/node_modules/aws-sdk/lib/param_validator.js:40:28)

**Comment by tylerlong** [comment]
I think it has something to do with Amazon Lex setup. I didn't write the documentation for that part.

I will update this repo soon.

**Comment by tylerlong** [comment]
README Updated.
